export interface CelestialGas {
  name: string;
  percent: number;
}

export interface CelestialBody {
  id:
    | 'sun'
    | 'mercury'
    | 'venus'
    | 'earth'
    | 'mars'
    | 'jupiter'
    | 'saturn'
    | 'uranus'
    | 'neptune'
    | 'pluto';
  name: string;
  subtitle: string;
  classification:
    | 'G-Type Main-Sequence Star'
    | 'Terrestrial Rocky Planet'
    | 'Gas Giant'
    | 'Ice Giant'
    | 'Kuiper Belt Dwarf Planet';
  orderFromSun: number;
  distanceAU: number;
  distanceKm: string;
  orbitalPeriodDisplay: string;
  orbitalVelocity: string;
  rotationPeriodDisplay: string;
  axialTiltDeg: number;
  radiusKm: number;
  radiusEarthRatio: number;
  massKg: string;
  massEarthRatio: number;
  surfaceGravity: string;
  temperature: {
    min: string;
    mean: string;
    max: string;
    description: string;
  };
  atmosphere: {
    pressure: string;
    summary: string;
    gases: CelestialGas[];
  };
  moonsCount: number;
  notableMoons: string[];
  hasRings: boolean;
  ringsDescription?: string;
  accentColor: string;
  summary: string;
  geology: string;
  exploration: string[];
  astrobiology: string;
  funFact: string;
  textures: {
    diffuse: string;
    bump?: string;
    clouds?: string;
    ringColor?: string;
    ringPattern?: string;
  };
}

export const solarBodies: CelestialBody[] = [
  {
    id: 'sun',
    name: 'The Sun',
    subtitle: 'Sol · The Heart of the Solar System',
    classification: 'G-Type Main-Sequence Star',
    orderFromSun: 0,
    distanceAU: 0,
    distanceKm: '0 km',
    orbitalPeriodDisplay: '~230 million years (around Galactic Center)',
    orbitalVelocity: '220 km/s (Galactic Orbit)',
    rotationPeriodDisplay: '25 days (Equator) to 35 days (Poles)',
    axialTiltDeg: 7.25,
    radiusKm: 696340,
    radiusEarthRatio: 109.2,
    massKg: '1.989 × 10³⁰ kg',
    massEarthRatio: 333000,
    surfaceGravity: '274.0 m/s² (28.0 g)',
    temperature: {
      min: '5,500 °C (Photosphere)',
      mean: '15,000,000 °C (Core)',
      max: '2,000,000 °C (Corona)',
      description: 'Thermonuclear fusion in the core generates energy that radiates into deep space.',
    },
    atmosphere: {
      pressure: 'Photosphere: ~0.868 kPa · Core: 26.5 PPa',
      summary: 'Plasma solar atmosphere composed of the photosphere, chromosphere, and superheated corona.',
      gases: [
        { name: 'Hydrogen (H)', percent: 73.4 },
        { name: 'Helium (He)', percent: 24.8 },
        { name: 'Oxygen (O)', percent: 0.77 },
        { name: 'Carbon (C)', percent: 0.29 },
        { name: 'Iron (Fe) & Others', percent: 0.74 },
      ],
    },
    moonsCount: 0,
    notableMoons: [],
    hasRings: false,
    accentColor: '#f59e0b',
    summary:
      'The gravitational anchor and primary energy source of our planetary system, containing 99.86% of the total mass in the entire solar system.',
    geology:
      'A nearly perfect sphere of hot plasma, energized by nuclear fusion of hydrogen into helium at its core (converting 600 million tons of hydrogen per second). Driven by convective dynamos, its magnetic field generates sunspots, solar flares, and coronal mass ejections.',
    exploration: [
      'SOHO (ESA/NASA, 1995–present): 24/7 observation of solar dynamics and space weather.',
      'Solar Dynamics Observatory (SDO, 2010): Ultra-HD multi-wavelength extreme UV imaging.',
      'Parker Solar Probe (NASA, 2018–present): Humanity’s first spacecraft to repeatedly "touch the Sun", flying through the corona at over 600,000 km/h.',
    ],
    astrobiology:
      'While the Sun itself cannot host life, its stable 4.6-billion-year main-sequence luminosity established and sustains the circumstellar habitable zone permitting liquid water on Earth.',
    funFact:
      'Light generated by fusion in the Sun’s core takes between 100,000 and 200,000 years to reach the surface, but then travels to Earth in just 8 minutes and 20 seconds.',
    textures: {
      diffuse: '/textures/planets/sun.jpg',
    },
  },
  {
    id: 'mercury',
    name: 'Mercury',
    subtitle: 'The Scalloped Iron World',
    classification: 'Terrestrial Rocky Planet',
    orderFromSun: 1,
    distanceAU: 0.387,
    distanceKm: '57.9 million km',
    orbitalPeriodDisplay: '88.0 Earth days',
    orbitalVelocity: '47.4 km/s',
    rotationPeriodDisplay: '58.6 Earth days (3:2 spin-orbit resonance)',
    axialTiltDeg: 0.034,
    radiusKm: 2439.7,
    radiusEarthRatio: 0.383,
    massKg: '3.301 × 10²³ kg',
    massEarthRatio: 0.055,
    surfaceGravity: '3.7 m/s² (0.38 g)',
    temperature: {
      min: '-180 °C (Night)',
      mean: '167 °C',
      max: '430 °C (Day)',
      description: 'Extreme thermal swings caused by its lack of atmosphere and proximity to the Sun.',
    },
    atmosphere: {
      pressure: '< 10⁻¹⁴ bar (Surface boundary exosphere)',
      summary: 'Ultra-tenuous exosphere continually stripped by the solar wind and replenished by meteoroid vaporisation.',
      gases: [
        { name: 'Oxygen (O)', percent: 42.0 },
        { name: 'Sodium (Na)', percent: 29.0 },
        { name: 'Hydrogen (H)', percent: 22.0 },
        { name: 'Helium (He)', percent: 6.0 },
        { name: 'Potassium (K)', percent: 1.0 },
      ],
    },
    moonsCount: 0,
    notableMoons: [],
    hasRings: false,
    accentColor: '#94a3b8',
    summary:
      'The smallest planet in the solar system, dominated by a gigantic metallic iron core comprising over 85% of its planetary radius.',
    geology:
      'Heavily cratered silicate crust scarred by lobate scarps (tectonic thrust faults) up to 3 km high, formed as the planet cooled and shrank by ~7 km in radius. Permanent shadow craters at the poles shelter extensive water ice deposits.',
    exploration: [
      'Mariner 10 (NASA, 1974–1975): First flyby mission; mapped 45% of the surface.',
      'MESSENGER (NASA, 2011–2015): First orbiter; confirmed polar water ice, volcanic smooth plains, and global contraction.',
      'BepiColombo (ESA/JAXA, 2018–present): Dual orbiter currently completing gravitational flybys.',
    ],
    astrobiology:
      'Considered inhospitable due to extreme radiation, solar wind bombardment, and temperature extremes, though its polar water ice preserves volatile records from the early solar system.',
    funFact:
      'Because of its 3:2 spin-orbit resonance, a single solar day on Mercury (from sunrise to sunrise) lasts exactly two Mercury years (176 Earth days).',
    textures: {
      diffuse: '/textures/planets/mercury.jpg',
      bump: '/textures/planets/mercury_bump.jpg',
    },
  },
  {
    id: 'venus',
    name: 'Venus',
    subtitle: 'The Superheated Greenhouse Twin',
    classification: 'Terrestrial Rocky Planet',
    orderFromSun: 2,
    distanceAU: 0.723,
    distanceKm: '108.2 million km',
    orbitalPeriodDisplay: '224.7 Earth days',
    orbitalVelocity: '35.0 km/s',
    rotationPeriodDisplay: '243.0 Earth days (Retrograde / Clockwise)',
    axialTiltDeg: 177.3,
    radiusKm: 6051.8,
    radiusEarthRatio: 0.949,
    massKg: '4.867 × 10²⁴ kg',
    massEarthRatio: 0.815,
    surfaceGravity: '8.87 m/s² (0.90 g)',
    temperature: {
      min: '438 °C',
      mean: '464 °C',
      max: '482 °C',
      description: 'Runaway greenhouse effect creates uniform, crushing furnace conditions planet-wide.',
    },
    atmosphere: {
      pressure: '93 bar (9.3 MPa — equivalent to 900 m underwater on Earth)',
      summary: 'Dense, opaque carbon dioxide envelope choked with sulfuric acid cloud decks.',
      gases: [
        { name: 'Carbon Dioxide (CO₂)', percent: 96.5 },
        { name: 'Nitrogen (N₂)', percent: 3.5 },
        { name: 'Sulfur Dioxide (SO₂)', percent: 0.015 },
        { name: 'Argon (Ar)', percent: 0.007 },
        { name: 'Water Vapor (H₂O)', percent: 0.002 },
      ],
    },
    moonsCount: 0,
    notableMoons: [],
    hasRings: false,
    accentColor: '#f59e0b',
    summary:
      'Earth’s twin in size and composition that suffered a catastrophic runaway greenhouse effect, transforming into a scorched volcanic hellscape.',
    geology:
      'Over 80% volcanic plains with thousands of volcanoes (including Maat Mons), shield fields, and arachnoids. Lacks global plate tectonics; instead, heat escapes via episodic mantle plumes and catastrophic global resurfacing events ~500 million years ago.',
    exploration: [
      'Venera 7–14 (USSR, 1970–1982): First spacecraft to land on another planet, transmitting color panoramas before succumbing to heat and pressure.',
      'Magellan (NASA, 1990–1994): Synthetic Aperture Radar mapped 98% of the surface at 100-meter resolution.',
      'Venus Express (ESA, 2005–2014) & Akatsuki (JAXA, 2015–present): Super-rotating atmospheric winds.',
      'DAVINCI+ & VERITAS (NASA, planned ~2030): Upcoming atmospheric probe and high-res radar.',
    ],
    astrobiology:
      'Surface conditions are completely sterile. However, the temperate upper cloud deck (50–65 km altitude) maintains 1 bar pressure and 20–30 °C temperatures, prompting intense interest in possible aerial microbial biospheres.',
    funFact:
      'Venus rotates backwards compared to most planets (retrograde) and so slowly that a Venusian day (243 Earth days) is longer than its entire year (225 Earth days).',
    textures: {
      diffuse: '/textures/planets/venus.jpg',
    },
  },
  {
    id: 'earth',
    name: 'Earth',
    subtitle: 'The Blue Oasis of Life',
    classification: 'Terrestrial Rocky Planet',
    orderFromSun: 3,
    distanceAU: 1.0,
    distanceKm: '149.6 million km',
    orbitalPeriodDisplay: '365.25 Earth days (1.00 year)',
    orbitalVelocity: '29.8 km/s',
    rotationPeriodDisplay: '23.93 hours (1 sidereal day)',
    axialTiltDeg: 23.44,
    radiusKm: 6371.0,
    radiusEarthRatio: 1.0,
    massKg: '5.972 × 10²⁴ kg',
    massEarthRatio: 1.0,
    surfaceGravity: '9.81 m/s² (1.00 g)',
    temperature: {
      min: '-89.2 °C (Antarctica)',
      mean: '15.0 °C',
      max: '56.7 °C (Death Valley)',
      description: 'Stabilized by a dynamic hydrological cycle, carbon silicate feedback, and plate tectonics.',
    },
    atmosphere: {
      pressure: '1.013 bar (101.3 kPa at sea level)',
      summary: 'Nitrogen-oxygen envelope with protective ozone layer, stabilized by biological activity.',
      gases: [
        { name: 'Nitrogen (N₂)', percent: 78.08 },
        { name: 'Oxygen (O₂)', percent: 20.95 },
        { name: 'Argon (Ar)', percent: 0.93 },
        { name: 'Carbon Dioxide (CO₂)', percent: 0.042 },
        { name: 'Water Vapor (H₂O)', percent: 0.4 },
      ],
    },
    moonsCount: 1,
    notableMoons: ['The Moon (Luna)'],
    hasRings: false,
    accentColor: '#34d399',
    summary:
      'The only known celestial body confirmed to harbor life, sustained by liquid surface oceans, active plate tectonics, and a protective geomagnetic shield.',
    geology:
      'Differentiated into an iron-nickel core (generating a dipole magnetic field), viscous silicate mantle, and a thin crust split into mobile tectonic plates. Constant continental drift recycles crust into the mantle via subduction zones.',
    exploration: [
      'Thousands of earth-observing orbital satellite constellations (Landsat, Sentinel, Terra/Aqua).',
      'The Moon landings (Apollo Program 1969–1972) returned 382 kg of lunar geological samples.',
      'Continuous human habitation aboard the International Space Station (ISS) since November 2000.',
    ],
    astrobiology:
      'Home to over 8.7 million species of eukaryotic life and untold trillions of prokaryotes, spanning deep oceanic hydrothermal vents, subglacial Antarctic lakes, and the high stratosphere.',
    funFact:
      'Earth’s Moon is unusually large relative to its parent planet (over 1/4 the diameter of Earth), stabilizing Earth’s axial tilt and preventing extreme chaotic climate swings.',
    textures: {
      diffuse: '/textures/planets/earth.jpg',
      bump: '/textures/planets/earth_bump.jpg',
      clouds: '/textures/planets/earth_clouds.jpg',
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    subtitle: 'The Rust-Red Desert World',
    classification: 'Terrestrial Rocky Planet',
    orderFromSun: 4,
    distanceAU: 1.524,
    distanceKm: '227.9 million km',
    orbitalPeriodDisplay: '687.0 Earth days (1.88 years)',
    orbitalVelocity: '24.1 km/s',
    rotationPeriodDisplay: '24.62 hours (1 Martian sol)',
    axialTiltDeg: 25.19,
    radiusKm: 3389.5,
    radiusEarthRatio: 0.532,
    massKg: '6.417 × 10²³ kg',
    massEarthRatio: 0.107,
    surfaceGravity: '3.72 m/s² (0.38 g)',
    temperature: {
      min: '-140 °C (Polar night)',
      mean: '-63 °C',
      max: '20 °C (Equatorial summer noon)',
      description: 'Thin atmosphere results in low thermal inertia and rapid diurnal swings.',
    },
    atmosphere: {
      pressure: '0.006 bar (610 Pa — less than 1% of Earth’s)',
      summary: 'Thin, carbon dioxide-dominated atmosphere vulnerable to solar wind ablation.',
      gases: [
        { name: 'Carbon Dioxide (CO₂)', percent: 95.32 },
        { name: 'Nitrogen (N₂)', percent: 2.6 },
        { name: 'Argon (Ar)', percent: 1.9 },
        { name: 'Oxygen (O₂)', percent: 0.13 },
        { name: 'Carbon Monoxide (CO)', percent: 0.08 },
      ],
    },
    moonsCount: 2,
    notableMoons: ['Phobos', 'Deimos'],
    hasRings: false,
    accentColor: '#f87171',
    summary:
      'A cold desert world rich in iron oxide minerals, preserving an ancient fossilized record of river deltas, lakes, and a thicker, warmer early atmosphere.',
    geology:
      'Features the largest volcano in the Solar System (Olympus Mons, 22 km tall) and the grandest rift canyon (Valles Marineris, 4,000 km long). Southern highlands are ancient and heavily cratered, while northern lowlands are smooth volcanic plains.',
    exploration: [
      'Viking 1 & 2 (NASA, 1976): First successful soft landings and bio-experiments.',
      'Curiosity (NASA, 2012–present): Explored Gale Crater, proving ancient lake habitability.',
      'Perseverance & Ingenuity (NASA, 2021–present): Exploring Jezero delta and caching rock cores for sample return.',
      'Tianwen-1 & Zhurong (CNSA, 2021): China’s first Mars lander/rover mission in Utopia Planitia.',
    ],
    astrobiology:
      'Primary target in the search for extraterrestrial life. Abundant geological evidence confirms standing liquid water and organic molecules in its Noachian period (~3.8 Ga). Modern search targets subsurface brine and deep aquifers.',
    funFact:
      'Mars hosts global dust storms that can envelop the entire planet for months, turning the sky an amber butterscotch and blocking out 99% of sunlight.',
    textures: {
      diffuse: '/textures/planets/mars.jpg',
      bump: '/textures/planets/mars_bump.jpg',
    },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    subtitle: 'The King of Planets',
    classification: 'Gas Giant',
    orderFromSun: 5,
    distanceAU: 5.204,
    distanceKm: '778.5 million km',
    orbitalPeriodDisplay: '11.86 Earth years',
    orbitalVelocity: '13.1 km/s',
    rotationPeriodDisplay: '9.93 hours (fastest planetary rotation)',
    axialTiltDeg: 3.13,
    radiusKm: 69911,
    radiusEarthRatio: 10.97,
    massKg: '1.898 × 10²⁷ kg',
    massEarthRatio: 317.8,
    surfaceGravity: '24.79 m/s² (2.53 g)',
    temperature: {
      min: '-145 °C (1 bar cloud top)',
      mean: '-110 °C',
      max: '24,000 °C (Core boundary)',
      description: 'Emits 1.67 times as much heat as it absorbs from the Sun due to internal Kelvin-Helmholtz gravitational compression.',
    },
    atmosphere: {
      pressure: 'Extends continuously into liquid interior; 1 bar level marks cloud top',
      summary: 'Dynamic multi-layered cloud system with alternating light zones and dark belts.',
      gases: [
        { name: 'Hydrogen (H₂)', percent: 89.8 },
        { name: 'Helium (He)', percent: 10.2 },
        { name: 'Methane (CH₄)', percent: 0.3 },
        { name: 'Ammonia (NH₃)', percent: 0.026 },
        { name: 'Hydrogen Deuteride', percent: 0.003 },
      ],
    },
    moonsCount: 95,
    notableMoons: ['Io', 'Europa', 'Ganymede', 'Callisto'],
    hasRings: true,
    ringsDescription: 'Faint, dark ring system made of dust shed by inner moons Metis and Adrastea.',
    accentColor: '#fbbf24',
    summary:
      'More massive than all other planets combined, Jupiter acts as a cosmic vacuum cleaner whose immense gravity shapes asteroid belts and shields inner worlds.',
    geology:
      'Lacks a solid surface. Ammonia cloud decks transition with depth into liquid molecular hydrogen, then into a deep mantle of exotic liquid metallic hydrogen under millions of atmospheres of pressure, surrounding a diffuse heavy-element core.',
    exploration: [
      'Pioneer 10 & 11 and Voyager 1 & 2 (1973–1979): Discovered rings, active volcanoes on Io, and ice crust on Europa.',
      'Galileo (NASA, 1995–2003): First orbiter; deployed atmospheric probe.',
      'Juno (NASA, 2016–present): Polar orbiter probing deep interior, core mass, and polar cyclonic storms.',
      'JUICE (ESA, 2023–en route): Exploring the icy Galilean ocean worlds Ganymede, Callisto, and Europa.',
    ],
    astrobiology:
      'While Jupiter’s atmosphere is likely uninhabitable, its moon Europa harbors a global subsurface saltwater ocean containing twice the water of all Earth’s oceans combined, warmed by tidal flexing and in contact with a rocky seabed.',
    funFact:
      'The Great Red Spot is a persistent anticyclonic storm larger than the entire Earth that has been raging for at least 350 years, with winds exceeding 430 km/h.',
    textures: {
      diffuse: '/textures/planets/jupiter.jpg',
    },
  },
  {
    id: 'saturn',
    name: 'Saturn',
    subtitle: 'The Jewel of the Solar System',
    classification: 'Gas Giant',
    orderFromSun: 6,
    distanceAU: 9.582,
    distanceKm: '1.434 billion km',
    orbitalPeriodDisplay: '29.46 Earth years',
    orbitalVelocity: '9.7 km/s',
    rotationPeriodDisplay: '10.7 hours',
    axialTiltDeg: 26.73,
    radiusKm: 58232,
    radiusEarthRatio: 9.14,
    massKg: '5.683 × 10²⁶ kg',
    massEarthRatio: 95.2,
    surfaceGravity: '10.44 m/s² (1.06 g)',
    temperature: {
      min: '-178 °C (Cloud tops)',
      mean: '-140 °C',
      max: '11,700 °C (Core boundary)',
      description: 'The least dense planet in the Solar System (density of 0.687 g/cm³ — it would float in water).',
    },
    atmosphere: {
      pressure: 'Vast gaseous envelope without sharp boundary; 1 bar cloud reference',
      summary: 'Golden ammonia-hazed atmosphere featuring a persistent hexagonal polar jet stream.',
      gases: [
        { name: 'Hydrogen (H₂)', percent: 96.3 },
        { name: 'Helium (He)', percent: 3.25 },
        { name: 'Methane (CH₄)', percent: 0.45 },
        { name: 'Ammonia (NH₃)', percent: 0.0125 },
        { name: 'Hydrogen Deuteride', percent: 0.011 },
      ],
    },
    moonsCount: 146,
    notableMoons: ['Titan', 'Enceladus', 'Mimas', 'Iapetus', 'Rhea'],
    hasRings: true,
    ringsDescription: 'Spectacular ring system spanning 282,000 km wide but only ~10 to 30 meters thick, composed of 99% pure water ice particles.',
    accentColor: '#eab308',
    summary:
      'Famed for its majestic, dazzling ring system and an extraordinarily diverse family of 146 confirmed moons, including hydrocarbon-rich Titan and cryovolcanic Enceladus.',
    geology:
      'Similar to Jupiter with a gaseous exterior giving way to liquid molecular and metallic hydrogen. The north pole hosts a mysterious geometric hexagon jet stream 30,000 km across that has remained stable for decades.',
    exploration: [
      'Pioneer 11 and Voyager 1 & 2 (1979–1981): First close-up looks at ring structure and Titan’s thick smoggy atmosphere.',
      'Cassini-Huygens (NASA/ESA, 2004–2017): Spent 13 years orbiting Saturn; landed the Huygens probe on Titan and discovered active water ice geysers erupting from Enceladus’s south pole.',
    ],
    astrobiology:
      'Saturn’s tiny moon Enceladus is one of the highest-priority astrobiology targets in science. Hydrothermal vents on its ocean floor erupt organic-rich plumes directly into space through fissures called "Tiger Stripes".',
    funFact:
      'Saturn’s rings are geologically young—likely between 10 and 100 million years old (formed during the age of the dinosaurs)—and are being drained by "ring rain" into Saturn, possibly vanishing within 300 million years.',
    textures: {
      diffuse: '/textures/planets/saturn.jpg',
      ringColor: '/textures/planets/saturn_ring.png',
      ringPattern: '/textures/planets/saturn_ring_pattern.png',
    },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    subtitle: 'The Tilted Ice Giant',
    classification: 'Ice Giant',
    orderFromSun: 7,
    distanceAU: 19.20,
    distanceKm: '2.871 billion km',
    orbitalPeriodDisplay: '84.01 Earth years',
    orbitalVelocity: '6.8 km/s',
    rotationPeriodDisplay: '17.24 hours (Retrograde)',
    axialTiltDeg: 97.77,
    radiusKm: 25362,
    radiusEarthRatio: 3.98,
    massKg: '8.681 × 10²⁵ kg',
    massEarthRatio: 14.54,
    surfaceGravity: '8.69 m/s² (0.89 g)',
    temperature: {
      min: '-224 °C (Coldest measured planetary atmosphere)',
      mean: '-195 °C',
      max: '4,700 °C (Core)',
      description: 'Uniquely low internal heat emission compared to all other giant planets.',
    },
    atmosphere: {
      pressure: 'Thick hydrogen-helium-methane mantle; 1.2 bar haze layer',
      summary: 'Pale aquamarine atmosphere where methane absorbs red light, giving the planet its serene cyan hue.',
      gases: [
        { name: 'Hydrogen (H₂)', percent: 82.5 },
        { name: 'Helium (He)', percent: 15.2 },
        { name: 'Methane (CH₄)', percent: 2.3 },
        { name: 'Hydrogen Deuteride', percent: 0.009 },
        { name: 'Ammonia & Water', percent: 0.001 },
      ],
    },
    moonsCount: 28,
    notableMoons: ['Miranda', 'Ariel', 'Umbriel', 'Titania', 'Oberon'],
    hasRings: true,
    ringsDescription: 'Dark, narrow vertical ring system consisting of 13 known rings made of carbonaceous debris.',
    accentColor: '#38bdf8',
    summary:
      'An enigmatic ice giant knocked completely on its side, rotating like a rolling ball as it orbits the Sun, experiencing 42 years of continuous sunlight followed by 42 years of darkness at each pole.',
    geology:
      'Composed primarily of a dense fluid mix of "icy" materials—water, ammonia, and methane—under high pressure, overlying a small silicate/iron-nickel core. Its off-center, tilted magnetic field is tilted 59° from its rotational axis.',
    exploration: [
      'Voyager 2 (NASA, January 1986): The only spacecraft to visit Uranus, discovering 10 new moons, 2 rings, and measuring its extreme magnetic field.',
      'Hubble Space Telescope & JWST: Periodic monitoring revealing seasonal auroral storms and ring system details.',
    ],
    astrobiology:
      'Extreme cold and lack of a stable liquid surface make the planet itself hostile. Several moons (such as Titania and Oberon) may harbor interior liquid water layers insulated by ammonia antifreeze.',
    funFact:
      'Uranus’s moon Miranda possesses the most chaotic cliff face in the Solar System: Verona Rupes, an almost vertical sheer wall estimated at 20 km (12 miles) high—10 times the depth of the Grand Canyon.',
    textures: {
      diffuse: '/textures/planets/uranus.jpg',
      ringColor: '/textures/planets/uranus_ring.png',
    },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    subtitle: 'The Supersonic Storm Giant',
    classification: 'Ice Giant',
    orderFromSun: 8,
    distanceAU: 30.05,
    distanceKm: '4.495 billion km',
    orbitalPeriodDisplay: '164.8 Earth years',
    orbitalVelocity: '5.4 km/s',
    rotationPeriodDisplay: '16.11 hours',
    axialTiltDeg: 28.32,
    radiusKm: 24622,
    radiusEarthRatio: 3.86,
    massKg: '1.024 × 10²⁶ kg',
    massEarthRatio: 17.15,
    surfaceGravity: '11.15 m/s² (1.14 g)',
    temperature: {
      min: '-218 °C (Cloud tops)',
      mean: '-201 °C',
      max: '7,000 °C (Core)',
      description: 'Radiates 2.61 times the energy it receives from the Sun, fueling furious supersonic weather.',
    },
    atmosphere: {
      pressure: 'Deep, dense gaseous envelope transitioning to supercritical fluid mantle',
      summary: 'Vibrant cobalt-blue atmosphere torn by the fastest recorded planetary winds in the Solar System.',
      gases: [
        { name: 'Hydrogen (H₂)', percent: 80.0 },
        { name: 'Helium (He)', percent: 19.0 },
        { name: 'Methane (CH₄)', percent: 1.5 },
        { name: 'Hydrogen Deuteride', percent: 0.019 },
        { name: 'Ethane & Ices', percent: 0.001 },
      ],
    },
    moonsCount: 16,
    notableMoons: ['Triton', 'Proteus', 'Nereid', 'Larissa'],
    hasRings: true,
    ringsDescription: 'Faint, dusty ring system with 5 named rings exhibiting strange clumpy arcs discovered by Voyager 2.',
    accentColor: '#3b82f6',
    summary:
      'The outermost major planet, an intensely cobalt-blue world whipped by supersonic winds exceeding 2,100 km/h and home to the captured dwarf planet Triton.',
    geology:
      'A fluid mantle of water, ammonia, and methane ices surrounding a rocky core with roughly the mass of Earth. High pressure deep within the ice mantle may cause methane molecules to break down into pure carbon crystals, creating "diamond rain".',
    exploration: [
      'Voyager 2 (NASA, August 1989): Flew 4,950 km above Neptune’s north pole, discovering the Great Dark Spot, active nitrogen geysers on Triton, and measuring its internal heat.',
      'JWST (2022): Captured the crispest view of Neptune’s rings and atmospheric methane cloud bands in over 30 years.',
    ],
    astrobiology:
      'Triton was likely captured from the Kuiper Belt and orbits backwards (retrograde). Tidal heating during capture generated a subsurface ocean beneath its nitrogen-ice crust that may persist to this day.',
    funFact:
      'Winds on Neptune reach up to 2,160 km/h (1,340 mph)—more than 1.5 times the speed of sound—making it by far the windiest planetary atmosphere in our solar system.',
    textures: {
      diffuse: '/textures/planets/neptune.jpg',
    },
  },
  {
    id: 'pluto',
    name: 'Pluto',
    subtitle: 'The Outpost of the Kuiper Belt',
    classification: 'Kuiper Belt Dwarf Planet',
    orderFromSun: 9,
    distanceAU: 39.48,
    distanceKm: '5.906 billion km',
    orbitalPeriodDisplay: '247.9 Earth years',
    orbitalVelocity: '4.7 km/s',
    rotationPeriodDisplay: '153.3 hours (6.39 Earth days · Retrograde)',
    axialTiltDeg: 122.53,
    radiusKm: 1188.3,
    radiusEarthRatio: 0.186,
    massKg: '1.303 × 10²² kg',
    massEarthRatio: 0.0022,
    surfaceGravity: '0.62 m/s² (0.063 g)',
    temperature: {
      min: '-240 °C',
      mean: '-229 °C',
      max: '-218 °C',
      description: 'Extremely cold; surface volatiles freeze out into solid nitrogen and methane frosts.',
    },
    atmosphere: {
      pressure: '1.0 Pa (10 microbars — 100,000 times thinner than Earth)',
      summary: 'Tenuous nitrogen-methane atmosphere with global blue haze layers that expands at perihelion and freezes at aphelion.',
      gases: [
        { name: 'Nitrogen (N₂)', percent: 99.0 },
        { name: 'Methane (CH₄)', percent: 0.5 },
        { name: 'Carbon Monoxide (CO)', percent: 0.5 },
      ],
    },
    moonsCount: 5,
    notableMoons: ['Charon', 'Nix', 'Hydra', 'Kerberos', 'Styx'],
    hasRings: false,
    accentColor: '#f43f5e',
    summary:
      'A dynamic world of nitrogen glaciers, water-ice mountains, and blue atmospheric hazes at the frontier of the Kuiper Belt, tidally locked in a binary dance with its moon Charon.',
    geology:
      'Home to Sputnik Planitia, a 1,000-km-wide basin of actively convecting nitrogen ice that forms the western lobe of Pluto’s famous "heart". Flanked by jagged mountains of rock-hard water ice up to 3.5 km tall and cryovolcanic domes like Wright Mons.',
    exploration: [
      'Discovered by Clyde Tombaugh in 1930 at Lowell Observatory in Flagstaff, Arizona.',
      'New Horizons (NASA, July 14, 2015): Historic flyby at 12,500 km altitude, revealing Pluto not as a dead cratered rock, but as an active, evolving world with glaciers and atmosphere.',
    ],
    astrobiology:
      'New Horizons data strongly suggests Pluto hosts a deep subsurface liquid water ocean beneath its thick water-ice shell, kept liquid by radioactive decay in its silicate core and dissolved ammonia acting as an antifreeze.',
    funFact:
      'Pluto and its largest moon Charon form a true double-planet system: their center of gravity (barycenter) lies in open space above Pluto’s surface, and both bodies keep the exact same face locked toward each other forever.',
    textures: {
      diffuse: '/textures/planets/pluto.jpg',
    },
  },
];
