export type Category = 'Planet'|'Life'|'Climate'|'Extinction'|'Humanity'|'Migration'|'Civilization';
export type EarthEvent = {id:string;age:number;title:string;category:Category;date:string;description:string;importance:string;place:string;certainty:string;sources:string[];keywords?:string;location?:[number,number]};
export const sources:Record<string,{name:string;url:string}>={
 cryogenian:{name:'Thomas & Catling (2024) · Cryogenian glaciations',url:'https://www.nature.com/articles/s41467-024-51412-8'},
 earlyClimate:{name:'NASA Astrobiology · Habitability of the young Earth',url:'https://astrobiology.nasa.gov/news/habitability-of-the-young-earth-could-boost-the-chances-of-life-elsewhere/'},
 earlyWater:{name:'John W. Valley · A Cool Early Earth?',url:'https://astrobiology.nasa.gov/nai/media/medialibrary/2013/10/Cooler-Early-Earth-Article.pdf'},
 oceania:{name:'Skoglund et al. (2016) · Peopling of the Southwest Pacific',url:'https://www.broadinstitute.org/publications/broad13426'},
 polynesia:{name:'Ioannidis et al. (2021) · Paths and timings of Polynesian settlement',url:'https://escholarship.org/uc/item/8r28n2r7'},
 usgs:{name:'USGS · Age of the Earth',url:'https://pubs.usgs.gov/gip/geotime/age.html'},
 ics:{name:'ICS · International Chronostratigraphic Chart (2024/12)',url:'https://stratigraphy.org/ICSchart/ChronostratChart2024-12.pdf'},
 paleo:{name:'Scotese & Wright (2018) · PALEOMAP PaleoDEMs',url:'https://www.earthbyte.org/paleodem-resource-scotese-and-wright-2018/'},
 nasa:{name:'NASA · Blue Marble Next Generation',url:'https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/base-map/'},
 life:{name:'Natural History Museum · Origins of life',url:'https://www.nhm.ac.uk/discover/origin-of-life-on-earth.html'},
 snow:{name:'NASA GISS · Snowball Earth',url:'https://www.giss.nasa.gov/research/features/201508_slushball/'},
 extinction:{name:'Natural History Museum · Mass extinctions',url:'https://www.nhm.ac.uk/discover/what-is-mass-extinction-and-are-we-facing-a-sixth-one.html'},
 kpg:{name:'Natural History Museum · Dinosaur extinction',url:'https://www.nhm.ac.uk/discover/dinosaur-extinction.html'},
 triassic:{name:'Natural History Museum · Triassic world',url:'https://www.nhm.ac.uk/discover/the-triassic-period-the-rise-of-the-dinosaurs.html'},
 human:{name:'Smithsonian · Human evolution evidence',url:'https://humanorigins.si.edu/evidence'},
 sapiens:{name:'Smithsonian · Homo sapiens',url:'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens'},
 sahul:{name:'Bird et al. (2019) · Settlement of Sahul',url:'https://www.nature.com/articles/s41598-019-42946-9'},
 plates:{name:'Peter Bird (2003) · PB2002 plate boundaries',url:'https://github.com/fraxen/tectonicplates'},
 agriculture:{name:'Smithsonian · Humans change the world',url:'https://humanorigins.si.edu/human-characteristics/humans-change-world'},
 moon:{name:'NASA · Moon formation',url:'https://science.nasa.gov/moon/formation/'},
 migration:{name:'Bergström et al. (2021) · Origins of modern human ancestry',url:'https://www.nature.com/articles/s41586-021-03244-5'},
 americas:{name:'USGS · White Sands footprints',url:'https://www.usgs.gov/news/national-news-release/study-confirms-age-oldest-fossil-human-footprints-north-america'},
 sea:{name:'NASA GISS · Sea level after the ice melted',url:'https://www.giss.nasa.gov/research/briefs/2007_gornitz_09/'},
 cities:{name:'The Metropolitan Museum · Uruk, the first city',url:'https://www.metmuseum.org/pt/essays/uruk-the-first-city'},
 egypt:{name:'Egyptian Ministry of Tourism and Antiquities · Early Dynastic Period',url:'https://egymonuments.gov.eg/en/historical-periods/early-dynastic-period'},
 indus:{name:'Harappa Archaeological Research Project · Excavation chronology',url:'https://www.harappa.com/content/recent-indus-discoveries-and-highlights-excavations-harappa-1998-2000'},
 china:{name:'The Metropolitan Museum · Asian art guide',url:'https://www.metmuseum.org/-/media/files/learn/family-map-and-guides/asianart_family_guide_web.pdf?sc_lang=en'},
 olmec:{name:'The Metropolitan Museum · Olmec art',url:'https://www.metmuseum.org/es/essays/olmec-art'},
 oxygen:{name:'Lyons et al. (2014) · Rise of oxygen',url:'https://www.nature.com/articles/nature13068'},
 permianDating:{name:'Burgess et al. (2014) · High-precision end-Permian timeline',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3948271/'},
 latePaleoClimate:{name:'Brocklehurst et al. (2018) · Carboniferous–Permian environments',url:'https://www.nature.com/articles/s41467-018-07623-x'},
 pangaeaAridity:{name:'Zhang et al. (2023) · Permian aridification of Pangaea',url:'https://www.nature.com/articles/s43247-023-00976-2'},
 triassicClimate:{name:'Wu et al. (2025) · Early Triassic vegetation and super-greenhouse climate',url:'https://www.nature.com/articles/s41467-025-60396-y'},
}
const E=(id:string,age:number,title:string,category:Category,date:string,description:string,importance:string,place:string,certainty:string,refs:string[],location?:[number,number],keywords=''):EarthEvent=>({id,age,title,category,date,description,importance,place,certainty,sources:refs,location,keywords});
export const events:EarthEvent[]=[
E('formation',4540,'A planet is born','Planet','About 4.54 billion years ago','Rocky bodies collide and accrete around the young Sun. Gravity assembles Earth, while impacts and radioactive decay heat its interior.','Differentiation separates the metallic core from the rocky mantle—the beginnings of our planet’s structure.','Inner Solar System','Earth’s age is well constrained by radiometric dating; the displayed surface is an artistic physical illustration, not reconstructed geography.',['usgs']),
E('moon',4500,'The Moon takes shape','Planet','Roughly 4.5 billion years ago','The leading model begins with a giant collision between the young Earth and another planetary body. Debris collects into the Moon.','The Earth–Moon system emerges from an energetic early Solar System.','Earth–Moon system','A giant impact is the leading explanation; its exact timing and collision details remain debated.',['moon']),
E('oceans',4400,'The first oceans','Planet','Possible liquid water by about 4.4 billion years ago','Ancient zircon minerals suggest that liquid water and a cool crust existed surprisingly early. Earth was not a permanent magma ocean.','Liquid water creates environments in which early chemistry can become more complex.','Ancient crust; zircon evidence from Western Australia','Indirect mineral evidence; the size and persistence of early oceans are uncertain.',['earlyWater','earlyClimate','usgs']),
E('life',3500,'Life leaves its first traces','Life','At least about 3.5 billion years ago','Microbial communities leave evidence in ancient rocks. Older proposed traces of life remain actively debated.','For most of Earth’s history, the living world is microscopic.','Evidence includes Western Australia and southern Africa','Early microbial life is strongly supported; the exact origin of life is unknown.',['life'],undefined,'earliest microbes first life photosynthesis stromatolites'),
E('kenorland',2700,'Early continents converge','Planet','Around 2.7 billion years ago','Ancient continental cores grow and collide. Kenorland is one proposed reconstruction of their arrangement.','Repeated assembly and breakup begin a long supercontinent story.','Ancient continental cratons','Kenorland and the still older proposed Vaalbara are debated. No definitive global map is shown.',['paleo'],undefined,'Vaalbara Kenorland'),
E('oxygen',2400,'A breath of change','Life','About 2.4 billion years ago','Oxygen produced by photosynthetic microbes begins to accumulate persistently in the atmosphere, transforming surface chemistry.','The Great Oxidation Event changes which metabolisms and environments can thrive.','Atmosphere and oceans','The broad transition is established; timing, oxygen levels and feedbacks have uncertainties.',['oxygen'],undefined,'Great Oxidation Event oxygen photosynthesis'),
E('nuna',1800,'Nuna: a gathering of continents','Planet','Approximately 1.8–1.5 billion years ago','Continental collisions assemble the supercontinent commonly called Nuna or Columbia.','Mountain belts preserve clues to a world that existed long before animals.','Continental cratons worldwide','Proposed configurations differ; this deep-time globe is illustrative.',['paleo'],undefined,'Columbia supercontinent'),
E('cells',1650,'More complex cells','Life','By roughly 1.6 billion years ago','The fossil record contains early eukaryotes: organisms with complex cellular organization, including a nucleus.','Eukaryotic cells are the lineage from which animals, plants and fungi eventually arise.','Ancient marine environments','Fossil interpretation and the earlier origin of the lineage remain debated.',['life'],undefined,'eukaryotes multicellular'),
E('rodinia',1000,'The world of Rodinia','Planet','Around 1 billion years ago','Most major continental blocks are thought to have been assembled into Rodinia before later rifting apart.','Continental breakup alters coastlines, weathering and the chemistry of the oceans.','Global continental assembly','Rodinia is a scientific hypothesis with competing arrangements; no exact land positions are implied here.',['paleo']),
E('snowball',700,'An almost frozen world','Climate','Cryogenian glaciations, about 720–635 million years ago','Ice reaches low latitudes during two exceptionally severe glaciations. The extent of open ocean is still debated.','These extremes test the resilience of microbial ecosystems and reshape the planet’s chemical cycles.','Global; low-latitude glacial deposits','Severe global glaciation is well supported; hard-snowball and slushball scenarios differ.',['snow']),
E('cryogenian-interlude',650,'Between the great freezes','Climate','A nonglacial interval between the Sturtian and Marinoan glaciations','The Sturtian ice age ends. An interval without the same widespread glaciation separates it from the later Marinoan freeze; the Cryogenian was not one continuous ice age.','Separating these episodes reveals repeated transitions in climate and ocean conditions.','Global stratigraphic records','The Marinoan onset remains uncertain. The displayed ice-free surface is a schematic contrast, not a map of measured global ice extent.',['cryogenian']),
E('marinoan',640,'The later great freeze','Climate','Marinoan glaciation; ending about 635 million years ago','Another severe glaciation brings ice to low latitudes. Its end marks a major transition into the Ediacaran Period.','Glacial retreat changes ocean chemistry and leaves distinctive deposits above glacial rocks.','Global; glacial deposits and overlying cap carbonates','The termination is better constrained than the onset. Ice coverage and the speed of the displayed retreat are illustrative.',['cryogenian','snow']),
E('ediacaran',575,'Life grows large','Life','Around 575 million years ago','Ediacaran communities include large, soft-bodied organisms with unfamiliar forms.','Complex ecosystems predate the familiar animal groups of the Cambrian.','Ancient seafloors','Fossils are well documented; the relationships of many organisms remain unresolved.',['life'],undefined,'Ediacaran Pannotia'),
E('cambrian',535,'An explosion of possibilities','Life','Cambrian diversification, about 539–520 million years ago','Animal body plans and ecosystems diversify over millions of years. Shells, skeletons and more complex food webs become widespread.','Many major animal groups appear in the fossil record during this interval.','Shallow marine environments','Diversification is established; its pace, causes and preservation biases are studied.',['life','ics'],undefined,'Cambrian explosion fish'),
E('plants',470,'Life reaches the land','Life','By around 470 million years ago','Microscopic spores record early land plants. Their descendants gradually transform soils and landscapes.','Land plants connect atmospheric carbon, weathering and the food webs of terrestrial ecosystems.','Moist continental environments','Spore evidence gives minimum ages, not an exact first arrival.',['life'],undefined,'first plants colonization land'),
E('ordovician',444,'The seas fall silent','Extinction','End-Ordovician, about 444 million years ago','Cooling, glaciation and sea-level change accompany severe losses in marine life, followed by another extinction pulse.','One of the Big Five mass extinctions reorganizes marine ecosystems. Rough estimates suggest about 85% species loss.','Global oceans','Magnitude estimates depend on fossil sampling; multiple environmental stresses interacted.',['extinction','ics']),
E('land-animals',420,'Animals explore the land','Life','Silurian–Devonian, roughly 430–390 million years ago','Arthropods establish terrestrial communities. Later, vertebrate lineages acquire adaptations for life in shallow water and on land.','The continents become living landscapes. The water-to-land transition is gradual and branching.','Continental margins and wetlands','Earliest terrestrial records are incomplete; no single date represents all land animals.',['life','ics'],undefined,'first land animals arthropods'),
E('devonian',372,'A prolonged crisis','Extinction','Late Devonian pulses, roughly 372–359 million years ago','Repeated environmental disruptions and oxygen-poor seas devastate reef builders and other marine groups.','This extinction unfolds in several episodes, not a single catastrophe. About three-quarters of species may be lost.','Global oceans','The triggers and relative roles of climate, volcanism and ecosystem change remain debated.',['extinction','ics']),
E('forests',310,'The age of great forests','Life','Carboniferous, around 310 million years ago','Equatorial wetlands support extensive forests while drier habitats and a major southern ice sheet occupy other regions. Burial of organic matter forms many coal deposits, while early amniotes diversify.','The amniotic egg helps vertebrates reproduce away from open water. Climate change later fragments many tropical wetlands and expands dryland habitats.','Equatorial Pangaean wetlands; glaciated southern Gondwana','Paleoelevation follows PALEOMAP. Surface colors distinguish broad humid, dry and icy settings but are not a fossil-calibrated vegetation map.',['ics','life','latePaleoClimate','paleo'],undefined,'reptiles synapsids amphibians Carboniferous Gondwana ice age'),
E('pangaea',280,'One vast supercontinent','Planet','Pangaea, around 300–200 million years ago','Continental collisions unite much of the world’s land. An immense surrounding ocean, Panthalassa, contrasts with a strongly seasonal and increasingly arid continental interior.','Pangaea’s assembly and eventual breakup shape mountain belts, climate and the geography we inherit.','Pangaea and Panthalassa','Land and sea follow the PALEOMAP elevation model. Coastlines and heights are approximate; surface colors summarize broad climate evidence rather than exact biome boundaries.',['paleo','ics','pangaeaAridity']),
E('permian',251.941,'The Great Dying','Extinction','About 252 million years ago','Enormous Siberian Traps eruptions drive rapid environmental change. Warming, ocean oxygen loss and acidification contribute to Earth’s most severe known mass extinction.','Marine and terrestrial ecosystems collapse; recovery takes millions of years. Species-loss estimates vary substantially by method.','Global; volcanism in Siberia','The marine extinction onset is dated to about 251.941 Ma; terrestrial timing and exact losses vary by region and method. The link to volcanism is strongly supported, while interacting mechanisms remain under study.',['permianDating','extinction','ics'],undefined,'Permian extinction Siberian Traps'),
E('dinosaurs',230,'The rise of dinosaurs','Life','Late Triassic, around 230 million years ago','Early dinosaurs live alongside many other reptile groups across a hot, strongly seasonal Pangaea. Mammal relatives also diversify in the same changing world.','Dinosaurs do not instantly dominate: their ecological expansion is a long process.','Pangaea','Fossil evidence is strong; earliest origins and evolutionary relationships continue to be refined. The broad arid-interior palette is illustrative, not an exact vegetation map.',['triassic','triassicClimate'],undefined,'first dinosaurs early mammals'),
E('triassic',201.4,'A volcanic turning point','Extinction','End-Triassic, about 201 million years ago','Central Atlantic Magmatic Province eruptions accompany major warming and ocean disruption.','Many competitors disappear, opening ecological space for dinosaurs. Approximate species-loss estimates are around 80%.','Pangaea’s developing rift system','Volcanism is a leading cause; losses vary across groups and ecosystems.',['triassic','extinction','ics']),
E('jurassic',150,'The age of giants','Life','Late Jurassic, around 150 million years ago','Dinosaurs flourish as Pangaea fragments. Laurasia and Gondwana separate; early birds emerge within theropod dinosaurs.','Continental separation creates new seas and increasingly distinct ecosystems.','Laurasia, Gondwana and the growing Atlantic','Geography follows a scientific reconstruction; vegetation and atmospheric decoration are illustrative.',['paleo','triassic','ics'],undefined,'birds Archaeopteryx Jurassic dinosaurs Laurasia Gondwana'),
E('flowers',100,'A flowering world','Life','Cretaceous, around 100 million years ago','Flowering plants become increasingly diverse. Warm oceans and high sea levels divide the continents with broad shallow seas.','Flowering plants and their ecological relationships transform terrestrial habitats.','Cretaceous continents','The fossil record constrains diversification, not one universal first-flower date.',['life','paleo','ics'],undefined,'angiosperms flowering plants'),
E('kpg',66,'The day everything changed','Extinction','66 million years ago','An asteroid strikes near present-day Chicxulub, Mexico. Dust and aerosols disrupt sunlight and food webs. Non-avian dinosaurs and many other groups disappear.','Roughly three-quarters of species are lost. Birds survive, and mammals later diversify into vacated ecological roles.','Chicxulub impact basin, Yucatán','The impact and extinction link is strongly established. The pin identifies the impact region in modern coordinates, not an exact reconstructed location.',['kpg','ics'],[21.4,-89.5],'Chicxulub asteroid impact K–Pg dinosaurs'),
E('mammals',56,'A new chapter for mammals','Life','Early Eocene, about 56 million years ago','Mammals diversify into many ecological roles. Early representatives of modern primate groups appear in a warm world.','Surviving lineages build new ecosystems after the end-Cretaceous extinction.','Forested continents','Fossil first appearances are minimum ages for lineages.',['life','ics'],undefined,'primates Paleogene rise mammals'),
E('antarctica',34,'Antarctica freezes','Climate','Around 34 million years ago','A major Antarctic ice sheet develops near the Eocene–Oligocene transition as the global climate cools.','Long-term cooling and ice-sheet growth move Earth toward the icehouse world of later human evolution.','Antarctica','The transition is recorded in marine sediments; ice extent varies over time.',['paleo','ics']),
E('grasslands',20,'Changing landscapes','Life','Miocene, around 20 million years ago','Mammals and apes diversify as continents approach familiar positions. Grassland expansion proceeds at different times in different regions.','Changing habitats influence the evolutionary histories of many living groups.','Continental ecosystems','Regional histories differ; one date cannot represent a global habitat transition.',['human','ics'],undefined,'Neogene great apes'),
E('hominins',7,'Our branch begins','Humanity','Roughly 8–6 million years ago','The evolutionary lineages leading to humans and chimpanzees diverge. Early hominins combine traits in ways unlike any living species.','Human evolution is a branching history, not a ladder of progress.','Africa','The divergence interval and placement of early fossils remain uncertain.',['human'],[12,18],'first hominins'),
E('australopithecus',3.2,'Walking in two worlds','Humanity','Australopithecus afarensis, about 3.85–2.95 million years ago','These hominins walk upright while retaining adaptations useful in trees. The fossil nicknamed Lucy belongs to this species.','Bipedal walking predates the large brains characteristic of later humans.','Eastern Africa','Species range is based on known fossils and is not a complete population map.',['human'],[9,40],'Lucy australopithecines'),
E('habilis',2.1,'Early members of Homo','Humanity','Homo habilis, about 2.4–1.4 million years ago','Early Homo overlaps in time with other hominin populations. Stone-tool use predates and extends beyond a single species.','Technology and anatomy evolve in a diverse hominin landscape.','Eastern and southern Africa','Taxonomy and attribution of tools to particular species remain debated.',['human'],[-3,35],'Homo habilis'),
E('erectus',1.5,'A wider human world','Humanity','Homo erectus, about 1.9 million–110,000 years ago','Homo erectus and closely related populations disperse well beyond Africa, with evidence across Eurasia.','Long-lived, mobile populations show that dispersal began long before Homo sapiens.','Africa and Eurasia','Species definitions and regional fossil dates vary.',['human'],[1,113],'Homo erectus'),
E('neanderthals',.2,'Other ways to be human','Humanity','Neanderthals, about 400,000–40,000 years ago','Neanderthals inhabit western Eurasia. Denisovan-related populations are known from fossils and ancient DNA in Asia. Both interbreed with Homo sapiens.','Several human populations coexist and exchange genes; they are not consecutive stages.','Europe and Asia; selected fossil regions are shown','Known fossil locations do not establish continuous population boundaries, especially for Denisovans.',['human','migration'],[48,10],'Denisovans Neanderthals interbreeding'),
E('sapiens',.3,'Our shared beginnings','Humanity','Homo sapiens, since about 300,000 years ago','Our species emerges in Africa among connected and structured populations. Fossil and genetic evidence points to a complex, continent-wide history.','Every living person belongs to this species; our origins do not reduce to one isolated birthplace.','Africa','Age is approximate; a single point cannot represent the full geography of our origins.',['sapiens','migration'],[20,20],'first humans modern human Homo sapiens'),
E('out-africa',.065,'Beyond Africa','Migration','Major surviving ancestry expansions, roughly 70,000–50,000 years ago','Populations expand through southwest Asia and beyond. Earlier dispersals also occurred; the major ancestry expansion is not the first departure from Africa.','Branching movements and contact with other populations help shape the ancestry of people alive today.','Africa, southwest Asia and beyond','Routes are schematic hypotheses. Dates, repeated movements and population relationships remain subjects of research.',['migration','sapiens'],[24,40],'Out of Africa migration'),
E('sahul',.055,'Crossing into Sahul','Migration','By about 65,000–50,000 years ago','People reach the connected landmass of Australia and New Guinea. Low sea levels expose shelves, but Wallacea still requires sea crossings.','Human dispersal includes planned or repeated water crossings, not just walking across land bridges.','Southeast Asia, Wallacea and Sahul','Arrival dates and pathways remain debated. Shelf exposure is a coarse bathymetric illustration.',['sahul'],[-10,130],'Australia New Guinea Sunda'),
E('europe',.045,'Across Eurasia','Migration','By around 45,000 years ago','Homo sapiens populations spread across Europe and Asia and encounter other human groups.','Dispersal includes local persistence, replacement and interbreeding, rather than one uniform wave.','Europe and Asia','Routes indicate broad connections, not traced individual journeys.',['migration','human'],[47,15],'Europe East Asia Siberia'),
E('ice-age',.021,'A world of ice and land bridges','Climate','Last Glacial Maximum, about 26,500–19,000 years ago','Large ice sheets cover northern regions. Sea level is roughly 120 metres below today, exposing Beringia and broad shelves around Sunda and Sahul.','Lower seas open some connections, while ice sheets block others. A land connection does not itself establish when people used it.','Beringia, Sunda, Sahul and northern continents','This view uses a coarse modern elevation grid and approximate ice regions; it is not a detailed coastline reconstruction.',['sea','sahul','human'],[65,-170],'Bering land bridge Beringia LGM'),
E('americas',.023,'The peopling of the Americas','Migration','Presence by about 23,000–21,000 years ago; dispersals vary','Footprints at White Sands support a human presence during the Last Glacial Maximum. Coastal and interior dispersal histories remain debated.','The peopling of the Americas predates the once-favored single late-arrival scenario.','Beringia and the Americas','The route animation is schematic. Earliest arrivals, timing and routes are unresolved; it does not prove an ice-free corridor was usable then.',['americas','migration'],[32.8,-106.3]),
E('agriculture',.012,'Cultivating a new relationship','Civilization','Beginning roughly 12,000 years ago, varying by region','Communities domesticate plants and animals in several parts of the world through different processes and at different times.','Food production supports new forms of settlement while transforming ecosystems and human lives.','Multiple independent centers','This is a long, uneven transition, not a single global revolution.',['agriculture'],[35,40],'Agricultural Revolution Neolithic permanent settlements'),
E('cities',.0055,'The first cities','Civilization','Fourth millennium BCE onward','Urban settlements grow in Mesopotamia. Cities involve increasingly specialized work, institutions and long-distance exchange.','Larger settlements reorganize landscapes, resources and social life.','Mesopotamia, including Uruk','Urbanization is gradual; definitions of a city and dating vary.',['cities'],[31.3,45.6],'Mesopotamia Sumer Uruk Bronze Age'),
E('egypt',.0051,'Along the Nile','Civilization','Around 3100 BCE onward','Political unification and expanding institutions shape ancient Egypt around the Nile’s agricultural corridor.','River systems, seasonal water and human institutions together influence early states.','Nile Valley','A milestone in a longer regional history, not the beginning of settlement.',['egypt'],[26,31],'Ancient Egypt civilization'),
E('indus',.0046,'Cities of the Indus','Civilization','Mature Harappan phase, about 2600–1900 BCE','Urban networks develop across the Indus region, with distinctive infrastructure, exchange and crafts.','Civilization develops along multiple paths, not one line from a single origin.','South Asia','Dates describe a cultural phase rather than one founding event.',['indus'],[27.3,68.1],'Indus Valley Harappa Mohenjo-daro'),
E('china',.0036,'Early Chinese states','Civilization','Shang period, approximately 1600–1046 BCE','Bronze-working societies and early states develop in northern China; later Shang inscriptions provide written evidence.','Archaeology and texts reveal another distinct trajectory of urban and state development.','Yellow River region','Earlier complex societies precede this milestone; traditional and archaeological chronologies differ.',['china'],[36.1,114.3],'Chinese civilization Shang Bronze Age'),
E('pacific',.0033,'Oceans become pathways','Migration','Remote Oceania, from about 3,300 years ago; eastern Pacific later','Seafaring communities settle widely separated islands in several waves over millennia.','Navigation and maritime knowledge connect an immense ocean world.','Pacific Islands','The routes summarize connections; each archipelago has its own chronology.',['oceania','polynesia'],[-18,178],'Polynesia Pacific settlement Lapita'),
E('olmec',.0032,'Civilizations of the Americas','Civilization','Second millennium BCE onward','Complex societies develop independently in Mesoamerica and the Andes. Olmec centers are one part of this wider history.','The final chapter contains many regional centers, not a single global sequence of progress.','Mesoamerica and the Andes','The marker is representative, not the first civilization throughout the Americas.',['olmec','agriculture'],[18,-94.5],'Olmec Maya Andes Americas Iron Age'),
E('present',0,'The world we know','Planet','Present day','A blue world, shaped by billions of years of extraordinary change. Its continents are still moving, and its living systems continue to evolve.','We occupy an extraordinarily brief moment in a planetary story still being written.','Earth','Modern imagery is NASA’s July 2004 cloud-free composite, not a live satellite feed.',['nasa','ics','usgs'])
].sort((a,b)=>b.age-a.age);
export const periods=[['Quaternary',2.58],['Neogene',23.04],['Paleogene',66],['Cretaceous',143.1],['Jurassic',201.4],['Triassic',251.902],['Permian',298.9],['Carboniferous',358.86],['Devonian',419.62],['Silurian',443.1],['Ordovician',486.85],['Cambrian',538.8]] as const;
export function chronology(age:number){
 const eon=age>4031?'Hadean':age>2500?'Archean':age>538.8?'Proterozoic':'Phanerozoic';
 const era=eon==='Phanerozoic'?(age>251.902?'Paleozoic':age>66?'Mesozoic':'Cenozoic'):eon==='Proterozoic'?(age>1600?'Paleoproterozoic':age>1000?'Mesoproterozoic':'Neoproterozoic'):eon==='Archean'?(age>3600?'Eoarchean':age>3200?'Paleoarchean':age>2800?'Mesoarchean':'Neoarchean'):'';
 const period=eon==='Phanerozoic'?(periods.find(x=>age<=x[1])?.[0]??'Cambrian'):age<=1000?(age>720?'Tonian':age>635?'Cryogenian':'Ediacaran'):'';
 const epoch=age<=.0117?'Holocene':age<=2.58?'Pleistocene':age<=5.333?'Pliocene':age<=23.04?'Miocene':age<=33.9?'Oligocene':age<=56?'Eocene':age<=66?'Paleocene':'';
 return {eon,era,period,epoch};
}
// Boundary extinctions belong in the period that ends at the selected boundary.
export function chapterChronology(event:EarthEvent){return chronology(event.age+(event.category==='Extinction'?.01:0));}
export function formatAge(age:number,short=false){if(age<.000001)return 'Present day';if(age>=1000)return `${(age/1000).toLocaleString('en',{maximumFractionDigits:2})} ${short?'Ga':'billion years ago'}`;if(age>=1)return `${age.toLocaleString('en',{maximumFractionDigits:age<10?2:1})} ${short?'Ma':'million years ago'}`;return `${Math.round(age*1e6).toLocaleString('en')} ${short?'yr ago':'years ago'}`;}
export const scales=[{name:'Deep time',max:4540},{name:'Geological periods',max:540},{name:'Evolution',max:10},{name:'Human prehistory',max:.3},{name:'Civilization',max:.012}];
// The overview allocates meaningful space to each temporal order of magnitude.
const anchors=[4540,4000,3500,2500,1800,1000,700,540,420,300,200,100,66,23,5,.3,.07,.02,.012,.005,0];
export function toPosition(age:number,scale:number){if(scale)return 100*(1-Math.min(age,scales[scale].max)/scales[scale].max);for(let i=0;i<anchors.length-1;i++)if(age>=anchors[i+1])return 100*(i+(anchors[i]-age)/(anchors[i]-anchors[i+1]))/(anchors.length-1);return 100;}
export function fromPosition(pos:number,scale:number){if(scale)return scales[scale].max*(1-pos/100);const n=Math.min(anchors.length-1,Math.max(0,pos/100*(anchors.length-1)));const i=Math.min(anchors.length-2,Math.floor(n));return anchors[i]+(anchors[i+1]-anchors[i])*(n-i);}
export function nearestEvent(age:number){return events.reduce((best,e)=>Math.abs(toPosition(e.age,0)-toPosition(age,0))<Math.abs(toPosition(best.age,0)-toPosition(age,0))?e:best);}
// Approximate Cryogenian windows, following Thomas & Catling (2024).
// The Marinoan onset is uncertain; the ramp widths are visual transitions,
// not measured rates of ice growth or melting.
const smooth=(lo:number,hi:number,value:number)=>{const t=Math.max(0,Math.min(1,(value-lo)/(hi-lo)));return t*t*(3-2*t);};
export function cryogenianIce(age:number){
 const sturtian=smooth(659,661,age)*(1-smooth(715,717,age));
 const marinoan=smooth(635,636,age)*(1-smooth(644,645,age));
 return Math.max(sturtian,marinoan);
}
export function cryogenianClimate(age:number){
 if(age>717)return 'Before the Sturtian glaciation';
 if(age>659)return 'Sturtian glaciation';
 if(age>=645)return 'Between major glaciations';
 if(age>635)return 'Marinoan glaciation';
 return 'After the Marinoan glaciation';
}
// Broad late Paleozoic ice envelope for a schematic southern-Gondwana overlay.
// Individual ice margins fluctuated; this is not a gridded ice reconstruction.
export function latePaleozoicIce(age:number){return smooth(260,275,age)*(1-smooth(335,355,age));}
export function environment(age:number){return age>4460?{climate:'Impact-heated / cooling',air:'Primordial / outgassing',land:'Early crust formation'}:age>4031?{climate:'Cooling, with impacts',air:'Little free oxygen',land:'Early crust and oceans'}:age>2500?{climate:'Poorly constrained',air:'Very little free oxygen',land:'Growing continental cores'}:age>720?{climate:'Variable; proxy-limited',air:age>2000?'Oxygen rising':'Below modern oxygen',land:'Continental assembly and breakup'}:age>=635?{climate:cryogenianClimate(age),air:'Uncertain concentrations',land:'Breaking continental blocks'}:age>360?{climate:age>450?'Variable greenhouse':'Cooling toward an icehouse',air:'Oxygen varies strongly',land:'Dispersed continents'}:age>299?{climate:'Late Paleozoic icehouse; humid equator',air:'High oxygen; changing CO₂',land:'Pangaea assembles; southern ice'}:age>252?{climate:'Drying interior; southern ice wanes',air:'Variable O₂ and CO₂',land:'Pangaea'}:age>201?{climate:'Hot, strongly seasonal greenhouse',air:'CO₂ generally above modern',land:'Pangaea'}:age>66?{climate:'Predominantly greenhouse',air:'CO₂ above modern in many intervals',land:'Pangaea fragments'}:age>2.58?{climate:age>34?'Warm, then cooling':'Long-term icehouse',air:'CO₂ generally declines',land:'Toward modern continents'}:age>.0117?{climate:'Glacial–interglacial cycles',air:'Variable glacial CO₂',land:'Sea-level-dependent shelves'}:{climate:'Holocene interglacial',air:'About 21% oxygen',land:'Modern configuration'};}
export const featured=['formation','life','snowball','cambrian','pangaea','jurassic','kpg','sapiens','out-africa','ice-age','agriculture','present'];

export function lifeAt(age:number){return age>3500?{title:'Before the known fossil record',text:'The origin of life is unknown. The earliest well-established microbial record dates to about 3.5 billion years ago.'}:age>1600?{title:'A microbial planet',text:'Microbes dominate. Photosynthesis and changing ocean chemistry gradually transform the planet.'}:age>575?{title:'Complex cells, new possibilities',text:'Eukaryotes diversify. Multicellular organization evolves in multiple lineages.'}:age>538.8?{title:'The Ediacaran world',text:'Large soft-bodied organisms populate ancient seafloors before the Cambrian diversification.'}:age>470?{title:'A flourishing ocean world',text:'Marine animals diversify. Land remains largely without the complex ecosystems familiar today.'}:age>360?{title:'Life ventures onto land',text:'Plants and arthropods expand on land; vertebrate transitions follow gradually.'}:age>252?{title:'Forests and early amniotes',text:'Terrestrial ecosystems grow more complex. Synapsids and reptile lineages diversify.'}:age>201?{title:'Recovery and new lineages',text:'Ecosystems recover from the end-Permian crisis. Early dinosaurs and mammal relatives appear.'}:age>66?{title:'Dinosaurs, mammals and birds',text:'Dinosaurs diversify, mammals persist, and birds arise within the dinosaur family tree.'}:age>2.58?{title:'Mammals diversify',text:'Mammals occupy many ecological roles while birds continue their own dinosaur lineage.'}:age>.0117?{title:'Life through the ice ages',text:'Glacial cycles repeatedly shift coastlines, vegetation zones and habitats. Ecosystems change as species move, adapt or disappear.'}:{title:'A connected living planet',text:'Forests, grasslands, wetlands and oceans support interconnected ecosystems. The living world continues to change.'};}
// A coarse explanatory interpolation between selected published sea-level anchors,
// not a complete sea-level reconstruction or local relative sea-level model.
export function seaLevel(age:number){const knots=[[0,0],[.021,-120],[.05,-75],[.065,-85],[.125,5]];if(age>.125)return 0;for(let i=0;i<knots.length-1;i++){if(age<=knots[i+1][0]){const [a,h]=knots[i],[b,k]=knots[i+1];return h+(k-h)*(age-a)/(b-a);}}return 0;}

